##Variables that will be used on the site##

@SERVER = http://localhost:7000


###RUNNING The server ###

GET {{SERVER}}

###Register a new user

POST {{SERVER}}/api/user/register
content-type: application/json

{
    "email": "kwazi3@gmail.com",
    "name": "kwazi", 
    "password": "123567",
    "role": "admin"
}


####LOGIN 






