##Variables that will be used on the site##

@SERVER = http://localhost:7000


###RUNNING The server ###

GET {{SERVER}}

###Register a new user ####3

POST {{SERVER}}/api/user/register
content-type: application/json

{
    "email": "dudu77@gmail.com",
    "name": "Adi", 
    "password": "12356789",
    "role": "client" 
}

####LOGIN #####

POST {{SERVER}}/api/user/login 
content-type: application/json

{
    "name": "Adi",
    "email": "dudu77@gmail.com",
    "password": "12356789",
    "role": "client"
}




