##Variables that will be used on the site##

@SERVER = http://localhost:7000


###RUNNING The server ###

GET {{SERVER}}

###Register

POST {{SERVER}}/api/user/register
content-type: application/json

{
    "name": "lebo",
    "email": "lebo@gmail.com", 
    "password": "1234567"
}



